---
title: "Laporan Uji Asumsi Klasik"
output: pdf_document
params:
  var_normalitas: NULL
  hasil_normalitas: NULL
  interpretasi_normalitas: NULL
  plot_qq: NULL
  var_homogenitas: NULL
  grup_homogenitas: NULL
  hasil_homogenitas: NULL
  interpretasi_homogenitas: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(ggplot2)
```
***Laporan Uji Asumsi***
Laporan ini dibuat pada tanggal `r format(Sys.Date(), '%d %B %Y')`.

**1.Uji Normalitas**
*Variabel yang diuji:* `r params$var_normalitas`

```{r}
if (!is.null(params$hasil_normalitas)) {
  cat("### Hasil Uji\n\n```\n")
  cat(params$hasil_normalitas)
  cat("\n```\n\n")
  cat("**Interpretasi:** \n\n ", params$interpretasi_normalitas)
} else {
  cat("Uji Normalitas belum dijalankan.")
}
```
```{r}
if (!is.null(params$plot_qq)) { print(params$plot_qq) }
```

**2.Uji Homogenitas Varians**
*Variabel Dependen:* `r params$var_homogentias` *Variabel Grup:* `r params$grup_homogenitas`
```{r}
if (!is.null(params$hasil_homogenitas)) {
  cat("### Hasil Uji\n\n```\n")
  cat(params$hasil_homogenitas)
  cat("\n```\n\n")
  cat("**Interpretasi:** \n\n ", params$interpretasi_homogenitas)
} else {
  cat("Uji Homogenitas belum dijalankan.")
}
```


